apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmarker-config
data:
  postgres_host: postgres-service
  postgres_dbname: appdb
  postgres_port: "5432"


---
apiVersion: v1
kind: Secret
metadata:
  name: bookmarker-secrets
type: Opaque
data:
  postgres_username: cG9zdGdyZXNz
  postgres_password: cG9zdGdyZXNz

