apiVersion: v1
kind: Service
metadata:
  name: my-bookmarker-service
spec:
  type: NodePort
  selector:
    app: my-bookmarker
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30090

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-bookmarker-deployement
  labels:
    app: my-bookmarker-deployement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-bookmarker
  template:
    metadata:
      labels:
        app: my-bookmarker
    spec:
      containers:
      - image: rajeevdocker01/bookmarker-api
        name: bookmarker-api
        ports:
        - containerPort: 3000
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s

